services:

  # PostgreSQL: The world's most advanced open source database.
  postgres:
    image: postgres:15-alpine
    container_name: chess_db
    ports:
      - "5432:5432"
    volumes:
      - chessdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=bebra
      - POSTGRES_PASSWORD=bebra123456789
      - POSTGRES_DB=chess_backend

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - chessredisdata:/data

volumes:
  chessdata:
  chessredisdata: