server.port=8080
server.shutdown=graceful

spring.application.name=backend

spring.datasource.url=${DB_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.hikari.maximum-pool-size=15
spring.datasource.hikari.connection-timeout=15000

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

spring.data.redis.database=0
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=60000

jwt.secret =${JWT_SECRET}
python.service.url=http://python-service:8000

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yml
spring.liquibase.enabled=true