spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/chess_backend
spring.datasource.username=bebra
spring.datasource.password=bebra123456789

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.data.redis.database=0
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=60000
